name: CI

on:
  pull_request:
  push:
    branches: main

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - run: npm ci
      - run: npm lint:check
      - run: npm format:check
      - run: npm stylelint:check
