name: CI

on:
  pull_request:
  push:
    branches: main

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - npm: run ci
      - npm: run lint:check
      - npm: run format:check
      - npm: run stylelint:check
